### ISSUE TITLE
Use .typoscript fileedings for setup and constants

### ISSUE THREAD

**Issue by benjaminkott** [in2code-de/lux#1]
Please consider changing the setup and constants to typoscript files.

**Comment by einpraegsam** [comment]
Thx Benjamin,

I was not sure since which T3 version setup.typoscript was accepted. 8.7 supports the newer endings?

Alex

**Comment by benjaminkott** [comment]
Was introduced in 8.7 after the decision was made that `.typoscript` is the official ending. So it´s save to use and encouraged to do so.

**Comment by einpraegsam** [comment]
Thx, will be released in the upcoming version
