### ISSUE TITLE
Exception when creating a LinkListener

### ISSUE THREAD

**Issue by tritum** [in2code-de/lux#11]
Thank you guys for this awesome extension :) But ~~Houston~~, öhm in2code, we've got a problem.

In our setup we encounter an error message Unknown column 'title' in 'order clause'when creating a LinkListener in the backend. Seems to be related to Issue #8. It's caused by Configuration/TCA/tx_lux_domain_model_linkclick.php:14.

This issue can be fixed by replacing the word "title" with an existing field. For example

`default_sortby' => 'ORDER BY linklistener ASC`.

**Comment by einpraegsam** [comment]
Thx for your feedback, will check this as soon as possible

**Comment by tritum** [comment]
Awesome Alex. Keep on rocking!
~BJ

**Comment by einpraegsam** [comment]
Thx for your feedback, I just pushed a fix to develop.
This was no issue in the past because linklistener should be added via lux backend module.
