### ISSUE TITLE
Exception when blacklisting user

### ISSUE THREAD

**Issue by m-strotmeier** [in2code-de/lux#12]
(TYPO3 10.4.17 and EXT:lux 14.3.1)
When I blacklist a user via the leads module, I get the following error message:

```
Oops, an error occurred!
Column 'categoryscorings' cannot be null
```

User data in table `tx_lux_domain_model_visitor` is not set to blank, flag `blacklisted` is not set.

**Comment by einpraegsam** [comment]
I played a bit with different sql_mode settings.

I could reproduce this issue with this settings:
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

My first tests did not show any errors here:
`IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

Nevertheless I will fix it asap.

**Comment by einpraegsam** [comment]
Thx for reporting @m-strotmeier - I'm going to release a new bugfix version in the next minutes.

**Comment by m-strotmeier** [comment]
Hi @einpraegsam, I can confirm the new version is working (14.3.2). Thanks for your quick replies!
