### ISSUE TITLE
ke_search: no search terms tracked

### ISSUE THREAD

**Issue by hempelta** [in2code-de/lux#13]
I'm trying to include ke_search in the tracking. I checked your documentation.

lib.lux.settings.tracking._enable = 1
lib.lux.settings.tracking.search = tx_kesearch_pi1 [sword]

In the constants of the template:
plugin.tx_lux.settings.tracking.search = 1

plugin.tx_lux.settings.tracking.search = 1
lib.lux.settings.disableTrackingForBackendUsers = 0
Cache is emptied, tested with different browsers dev / live ... I can't find the error

However, no search terms are tracked.

![219258225_2987838581428478_3285604693149469720_n](https://user-images.githubusercontent.com/66489150/126515675-a9f20406-a656-43d7-9dc1-d33232a4dfc7.jpg)

**Comment by einpraegsam** [comment]
Hi and thx for giving feedback about the lux extension.

I just tested with this TypoScript setup:
```
lib.lux.settings {
    tracking {
        search {
            getParameters = tx_solr[q],tx_indexedsearch[sword],tx_kesearch_pi1[sword]
        }
    }
}

plugin.tx_lux_fe.settings < lib.lux.settings
module.tx_lux.settings < lib.lux.settings
luxConfigurationFieldIdentification.10.settings < lib.lux.settings
luxConfigurationFormIdentification.10.settings < lib.lux.settings
```

When I now open a page with and URL like `https://domain.org/suche?tx_kesearch_pi1[sword]=tester`, the result is visible in the dashboard:
![screenshot_dashboard](https://user-images.githubusercontent.com/89055/127182981-aecb3a06-92e2-41bc-9a03-ee8305ad7cc9.png)

Can you please test with the same TypoScript and give me feedback?

Greetings from Rosenheim

**Comment by hempelta** [comment]
Hello Alex, thx for your feedback.

I don't know exactly why yet, but now it seems to be working.

My typoscript was as given by you. I only adjusted the search parameter. In my opinion, it was okay beforehand.

before:
lib.lux.settings.tracking.search.getParameters = tx_kesearch_pi1[sword],tx_kesearch_pi1%5Bsword%5D

after:
lib.lux.settings.tracking.search.getParameters = tx_solr[q],tx_indexedsearch[sword],tx_kesearch_pi1[sword]


Then i updated everything, also in2code/lux (15.1.0 => 15.2.0).
Cleared all caches.
Tested with multiple browsers.
It works now :-)

![grafik](https://user-images.githubusercontent.com/66489150/128079604-66512cb2-d07b-4398-a1b5-c278f370bb91.png)

Greetings

**Comment by einpraegsam** [comment]
Nice that it works now. I also implemented ke_search terms to be respected by default since lux 15.2.0 (no additional configuration needed here).
