### ISSUE TITLE
Sql error

### ISSUE THREAD

**Issue by Fehndruid** [in2code-de/lux#15]
Hi, 
following error occurs as I try to open an old blog entry created with z7_blog extension:

`Expression #1 of ORDER BY clause is not in SELECT list, references column 'html-www-typo3db.tx_lux_domain_model_pagevisit.tstamp' which is not in SELECT list; this is incompatible with DISTINCT `

I am not sure about what caused the error. I haven't get how to debug typo3 and extensions until now.

Lux is the newest extension i have installed. Can you tell me whats wrong, if its isn't an error by Lux?

best wishes

**Comment by einpraegsam** [comment]
Thx for your feedback
That problem is related to your MySQL settings and a bug in lux.
I will provide a fix asap.

**Comment by einpraegsam** [comment]
Statusupdate: I just set my SQL settings to
`ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
I think the `ONLY_FULL_GROUP_BY` is the breaking point. But I could not reproduce this issue (clicked around in the backend).
So I'm still on it...

Note: I collegue of me posted yesterday that he had the same issue with the sql settings from above

**Comment by einpraegsam** [comment]
This problem is related to a bug in extbase:
https://forge.typo3.org/issues/94899

Nevertheless I will search for a faster solution (workarround)

**Comment by einpraegsam** [comment]
@Fehndruid I just release bugfix version 15.3.1 with a workarround. Can you confirm that the error is fixed?

**Comment by Fehndruid** [comment]
Version 15.3.1 is running, and 16.0.0 too, it's fixed. Really nice, I hadn't thought that I get help so quickly. Thanks, you are the best

**Comment by einpraegsam** [comment]
Fine! Thx for the final request
