### ISSUE TITLE
\WhichBrowser\Parser class is missing 

### ISSUE THREAD

**Issue by lenjka01** [in2code-de/lux#16]
Hi
When I click on Analyse in backend I get the following error:

Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1588337756: \WhichBrowser\Parser class is missing | In2code\Lux\Exception\ClassDoesNotExistException thrown in file /html/typo3/typo3conf/ext/lux/Classes/Domain/Repository/FingerprintRepository.php in line 56. Requested URL: https://www.mysite.de/typo3/index.php?route=%%2Fmodule%%2Flux%%2FLuxAnalysis&token=--AnonymizedToken--

**Comment by einpraegsam** [comment]
Hi, did you install the extension via composer as expected by manual?

**Comment by lenjka01** [comment]
Installed and updated from the TER

**Comment by einpraegsam** [comment]
So this is the problem. The package \WhichBrowser\Parser is not available here. Sorry but composer mode is needed.
