### ISSUE TITLE
Email4Link: ###TITLE### gets replaced with the current site title

### ISSUE THREAD

**Issue by schugabe** [in2code-de/lux#23]
If I insert a Email4Link all placeholders work but ###TITLE### always gets replaced with the site title and the js file of lux can't replace the title when the lightbox is opened.

Lux 20.2.2
TYPO3 10.4.22

**Comment by einpraegsam** [comment]
Okay, that remembers me to old times, when subparts and markers are used to integrate HTML into TYPO3. Do you have a "magic" function added to your TYPO3 that replaces ###TITLE### with a site title?

**Comment by schugabe** [comment]
We are using fluid and I'm not aware of any magic functions. The PageRenderer still sets the title marker for every page: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/Page/PageRenderer.php#L1885

**Comment by einpraegsam** [comment]
Strange, I can't reproduce this issue on some systems (10 and 11). Nevertheless, I think we should change all marker names to a less generic one (e.g. ###EMAIL4LINK_TITLE###).
