### ISSUE TITLE
Global config.linkVars settings are interfering with ajax requests

### ISSUE THREAD

**Issue by guelzow** [in2code-de/lux#24]
Hi everyone.

The page TypeNum is added globally to all linkVars here:
https://github.com/in2code-de/lux/blob/develop/Configuration/TypoScript/Lux/20_Configuration.typoscript#L2

When an other TypeNum is used (for example) an ajax search then it's TypeNum is added to every URL generated in the search.
That severely limits the usefulness of this search, because it always points back to the ajax search entrypoint.

Proposed solution:
Add the linkVars to their PageTypes locally, where they are used, and not globally where everybody else is using them.

Tobi

**Comment by einpraegsam** [comment]
Thx for the valuable feedback. I think you are right. We're going to change this in the near future.

**Comment by einpraegsam** [comment]
Thx is already fixed with 559e7e0aee3bf086fb38f56b7cffce3b6fc50ebd
Thx for your feedback

**Comment by guelzow** [comment]
And thx for fixing.
