### ISSUE TITLE
LUX destroys the ckeditor styling

### ISSUE THREAD

**Issue by moxface** [in2code-de/lux#26]
First of all super extension... but something is wrong (unfortunately).

When i install LUX, the RTE no longer works cleanly. It does not load the RTE CSS... Looks like crap anyway.

To test against I installed a fresh TYPO3 Composer instance. After installing LUX the RTE looks like this...

Key data:
PHP: 7.4
TYPO3: 10.4.28

composer.json
`{
	"name": "typo3/cms-base-distribution",
	"description" : "TYPO3 CMS Base Distribution",
	"license": "GPL-2.0-or-later",
	"config": {
		"allow-plugins": {
			"typo3/class-alias-loader": true,
			"typo3/cms-composer-installers": true
		},
		"platform": {
			"php": "7.4"
		},
		"sort-packages": true
	},
	"require": {
		"helhum/typo3-console": "^6.0.0",
		"in2code/lux": "^23.2",
		"typo3/cms-about": "^10.4.0",
		"typo3/cms-backend": "^10.4.0",
		"typo3/cms-belog": "^10.4.0",
		"typo3/cms-beuser": "^10.4.0",
		"typo3/cms-core": "^10.4.0",
		"typo3/cms-dashboard": "^10.4.0",
		"typo3/cms-extbase": "^10.4.0",
		"typo3/cms-extensionmanager": "^10.4.0",
		"typo3/cms-felogin": "^10.4.0",
		"typo3/cms-filelist": "^10.4.0",
		"typo3/cms-fluid": "^10.4.0",
		"typo3/cms-fluid-styled-content": "^10.4.0",
		"typo3/cms-form": "^10.4.0",
		"typo3/cms-frontend": "^10.4.0",
		"typo3/cms-impexp": "^10.4.0",
		"typo3/cms-info": "^10.4.0",
		"typo3/cms-install": "^10.4.0",
		"typo3/cms-recordlist": "^10.4.0",
		"typo3/cms-rte-ckeditor": "^10.4.0",
		"typo3/cms-seo": "^10.4.0",
		"typo3/cms-setup": "^10.4.0",
		"typo3/cms-sys-note": "^10.4.0",
		"typo3/cms-t3editor": "^10.4.0",
		"typo3/cms-tstemplate": "^10.4.0",
		"typo3/cms-viewpage": "^10.4.0"
	},
	"scripts":{
		"typo3-cms-scripts": [
			"typo3cms install:generatepackagestates",
			"typo3cms install:fixfolderstructure"
		],
		"post-autoload-dump": [
			"@typo3-cms-scripts"
		]
	}
}
`

<img width="953" alt="Bildschirmfoto 2022-05-27 um 22 31 58" src="https://user-images.githubusercontent.com/5691328/170786562-4a30aa17-b68e-4344-bd33-3354b851a8bb.png">

**Comment by einpraegsam** [comment]
Thx for using LUX. I hope this helps your marketing performance.
I just added a hint to FAQ that describes the problem and gives a hint https://github.com/in2code-de/lux/blob/develop/Documentation/Technical/FAQ/Index.md#ckeditor-seems-to-be-broken

Greetings, Alex
