### ISSUE TITLE
[BUG] LUX breaks CKEditor Config

### ISSUE THREAD

**Issue by grimmcreative** [in2code-de/lux#3]
If LUX is active in Extension Manager, CKEditor Configurations getting overwritten, no more individual Configuration is shown. 

Reproduce able with bootstrap_package

**Comment by einpraegsam** [comment]
Question: The CKEditor configuration is normally done in your sitepacke. I'm asking because if you require EXT:lux in your sitepackage, lux is loaded before your sitepackage, so your YAML-Configuration should work.
So you are using the YAML-Config from EXT:bootstrap_package?

**Comment by einpraegsam** [comment]
Any feedback for me? Do we have to add a toggle where the admin can set if CKEditor configuration should be added or not?

**Comment by grimmcreative** [comment]
Sorry. Yes a toggle would be great!

**Comment by einpraegsam** [comment]
Added a feature toggle in 4.1.0

**Comment by christophbee** [comment]
Hey! I am faced with the same problem. Where do I find this toggle feature?
Thank you

**Comment by einpraegsam** [comment]
Look at https://github.com/in2code-de/lux/blob/develop/Documentation/Technical/Installation/Index.md#extension-manager-settings for details
