### ISSUE TITLE
email4link and categoryscoring with file

### ISSUE THREAD

**Issue by FailXSiegen** [in2code-de/lux#35]
I add a lux-category in the file metadata.
I configure a link in the CKeditor and add the email4link feature.
The downloaded file does not count as a downlowd in the configured lux-category.

**Comment by einpraegsam** [comment]
Hi Felix,

thx for your feedback. Will dig into that issue and give you feedback.

Alex

**Comment by einpraegsam** [comment]
Hi, I just delivered this feature (technically it was a missing feature) in version 28.2.0

Thx for your feedback Felix
