### ISSUE TITLE
Table 'xxx.sys_language' doesn't exist

### ISSUE THREAD

**Issue by weisgerberm** [in2code-de/lux#40]
When I open the Analyze module and navigate to "Page views and downloads" in the tab, I get the error:

**(1/3) #1146 Doctrine\DBAL\Exception\TableNotFoundException
An exception occurred while executing a query: Table 'xxx.sys_language' doesn't exist**

When I look at the stack, this is what it does:

**at Doctrine\DBAL\Connection->convertExceptionDuringQuery(object(Doctrine\DBAL\Driver\Mysqli\Exception\ConnectionError), 'SELECT count(*) as count, pv.language, l.title FROM tx_lux_domain_model_pagevisit pv left join sys_language l on l.uid = pv.language left join tx_lux_domain_model_visitor v on v.uid = pv.visitor left join tx_lux_domain_model_categoryscoring cs on v.uid = cs.visitor where pv.crdate>1659564000 and pv.crdate<1691131900 group by pv.language, l.title order by count desc ', array(), array())**

Sounds like it has not yet been switched to the new language field of TYPO3 12

I use TYPO3 12.4.4 with bootstrap_package and PHP 8.2

**Comment by einpraegsam** [comment]
Thx for the feedback. We're going to check this as soon as possible.

**Comment by einpraegsam** [comment]
New versions released which prevent this error:
LUX 32.2.2 
LUXenterprise 36.1.0

**Comment by weisgerberm** [comment]
Thank you. I can confirm that it works

**Comment by einpraegsam** [comment]
Super, thx for your final feedback 💪
