### ISSUE TITLE
Bug: Setting Access rights not possible for Backend modules in TYPO3 12 

### ISSUE THREAD

**Issue by pulponair** [in2code-de/lux#41]
## Story
As an adiminstrator i want to  be able to set access rights to lux Backendmodules on a user/usergroup base.
This is not possible in TYPO3 V12 due to a missconfiguration in Configuration/Backend/Modules.php

## Tech. Details
Configuration/Backend/Modules.php currently sets the "access" key to "user,group" this is not a valid Configuration in TYPO3 Version 12 (See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/HowTo/BackendModule/ModuleConfiguration.html#confval-access)

It has to be just "user" :)

**Comment by einpraegsam** [comment]
Thx for your notice - I just released 33.0.1 which should fix this issue (and also released a new version of LUXletter with the same issue)
