### ISSUE TITLE
after database integrity check, mysql error

### ISSUE THREAD

**Issue by EnzephaloN** [in2code-de/lux#44]
Typo3 11.5.33 with lux 34.0.2

After doing database integrity check and database relation update I'm getting this error
````
Doctrine\DBAL\Exception\InvalidFieldNameException
An exception occurred while executing 'SELECT `uid`, `pid`, `title` FROM `tx_lux_domain_model_utm` WHERE `pid` NOT IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, 1, 4, 6, 7, 8, 9, 3, 5, 2]: Unknown column 'title' in 'field list'
````
when accessing db integrity check module.

**Comment by einpraegsam** [comment]
Thx for your post. Yes, there is no title field in UTM table. I will investigate how to fix this small issue.

**Comment by einpraegsam** [comment]
I think I found the small bug. I will release a 34.0.3 in a few minutes.

**Comment by EnzephaloN** [comment]
Thanx a lot!
