### ISSUE TITLE
Campaign -> A/B Testing Error when 'No data available yet'

### ISSUE THREAD

**Issue by simonzellneratcoma** [in2code-de/lux#46]
Hi,

i think i found an error, when the installation is empty, without visitors, and you click inside Campaign -> A/B Testing, an sql error is shown.

In my opinion only when has lux visitors must be call this function, otherwise the sql query isn't correct.
![Captura de pantalla 2024-04-11 a las 10 14 12 a  m](https://github.com/in2code-de/lux/assets/162999095/7440dcc0-0281-4810-a2ac-a8501931913a)

**Comment by einpraegsam** [comment]
Thx for the notification. I can reproduce this issue on an empty installation.

**Comment by einpraegsam** [comment]
I just released version 35.0.1 of LUX. This should fix this error.
Thank you for reporting.
