### ISSUE TITLE
Leads crashes on Companies overview page

### ISSUE THREAD

**Issue by AlenBilalovic** [in2code-de/lux#48]
Hello,

We have the companies tab in leads module crashing with following error
```
(1/1) #1484828466 TYPO3\CMS\Extbase\Persistence\Generic\Storage\Exception\BadConstraintException
The IN operator needs a non-empty value list to compare against. The given value list is empty.
```

It believe it is related to the fact that the tx_lux_domain_model_company database is empty.

But once we set up the scheduler command lux:setWiredmindCompanyInformation nothing happens.
No records are imported.
Important to note is the fact that anonymize ip is turned off.

On the scheduler part, might be that we missed a settings somewhere to make it work correctly.

Any feedback is appreciated.
If you need any additional data, just let me know.

Best Regards
Alen

**Comment by einpraegsam** [comment]
Hi Alen,

there are some questions that have to be answered.

1) Exception: 
Can you give me the version of LUX that you are using? In addition, a full backtrace would be fine to figure out where this error happened (We need the PHP class and line with the in() statement)

2) Using command lux:setWiredmindCompanyInformation:
This is only available with Wiredminds configuration (you would need a token for this service - see https://www.in2code.de/typo3-wiredminds-integration/ or https://www.in2code.de/en/typo3-wiredminds-integration/ for details).
If you already own a token and use the Wiredminds service, keep in mind, that wiredminds can only convert old visitors if there is an IP-address (not anonymized) in visitor table.

Looking for your feedback,

Alex

**Comment by AlenBilalovic** [comment]
Hi Alex,

Lux version: 33.3.1
Lux Enterprise version: 36.3.1

We already have a token and the anonymize ip option is disabled.
Ip's are saved fully in the tables (without ***); old ones with *** cannot be converted which is correct, but the new visitors with full ip are not processed at all with the scheduler.
Just executes successfully and the company table has no records added at all.

The error in question when accessing the companies tab in leads module which is partly correct since the company table is empty i figure.
![Screenshot 2024-05-03 at 09 01 15](https://github.com/in2code-de/lux/assets/48238084/527947ac-df1b-46ec-b14b-ca5c5c839361)

Best Regards
Alen

P.S.
Let me know if i can assist you in any other way.
Thanks for your efforts.

**Comment by einpraegsam** [comment]
Hi again,

thx for the version.
First of all: There where some bugfix releases. Did you already test with the latest version of LUX.

Beside that: I would need even more of the backtrace. I need the place where EXT:lux is involved. All functions in the screenshot are from extbase and are called after EXT:lux.

Thx, Alex

**Comment by einpraegsam** [comment]
Any feedback for me?

**Comment by AlenBilalovic** [comment]
Hi Alex,

Sorry for the delay.

All works as intended on latest versions.

Companies are imported correctly via scheduler and leads module throws no backend errors.

Will close this issue.

Thanks for your assist.

Best Regards
Alen

**Comment by einpraegsam** [comment]
Thx Alen for your final feedback
