### ISSUE TITLE
TYPO3 v12.4.14, LUX v35.2.0, thousands of WARNINGs like this:

### ISSUE THREAD

**Issue by helmut-winkelbach** [in2code-de/lux#51]
`Sat, 04 May 2024 07:43:22 +0200 [WARNING] request="261b83651b0c8" component="In2code.Lux.Controller.FrontendController": Error in FrontendController happened - {"code":1592581260,"message":"Stop tracking because of blacklisted user agent"}`

**Comment by einpraegsam** [comment]
Thx Helmut,

Such warnings are listed in the backend log?

Alex

**Comment by einpraegsam** [comment]
I just checked the code and those warnings are wanted to be logged to `var/log/typo3_[hash].log`. If you don't want those errors, you can increase the loglevel of TYPO3 - or disable for warnings:
```
$GLOBALS['TYPO3_CONF_VARS']['LOG']['TYPO3']['CMS']['Core']['Error']['writerConfiguration'] = [
    \TYPO3\CMS\Core\Log\LogLevel::WARNING => []
];
```

**Comment by einpraegsam** [comment]
No further feedback, I'm going to close this issue for now
