### ISSUE TITLE
"Last visit" in overview shows Date and Time of "first visit"

### ISSUE THREAD

**Issue by AlenBilalovic** [in2code-de/lux#52]
Hello,

Just noticed that in the overview the last visit does not match the lead preview times.
![CompanyOverview](https://github.com/in2code-de/lux/assets/48238084/1d10435b-8e93-4089-a521-3941fa8445c0)
![LeadPreview](https://github.com/in2code-de/lux/assets/48238084/5e215f96-f911-4e5b-b6c2-4afb60c10ee2)

Lux version 35.4.0
Luxenterprise version 39.1.1

Let me know if i can assist with anything else.

Thanks in advance and Best Regards
Alen

**Comment by einpraegsam** [comment]
Thx for reporting. Even if my test machine did not reflect the problem with (I guess your screenshot shows the company listview and a company detail) the last visit, I unified different methods between both screens now. 
So I pushed the change into develop branch.
Can you please test the latest change for me and give me feedback?
If this does not fix the problem, what's probably the point, I need more information from you or a dump of the pagvisit table related to the user from the screenshot.

**Comment by einpraegsam** [comment]
No feedback yet, I'm going to close this issue
