### ISSUE TITLE
Autoloaded typoscript add URL at the bottom of the page

### ISSUE THREAD

**Issue by martinpribylhd** [in2code-de/lux#53]
When you have installed the extension, but doesn't included typoscript Main TypoScript, then page.1518815717 add URL at the bottom of the page.

The image better shows what happen

When included Main TypoScript
<img width="760" alt="Screenshot 2024-07-19 at 21 02 22" src="https://github.com/user-attachments/assets/40891f8a-06c6-44d5-85a8-549e911ad672">

When NOT included Main TypoScript
<img width="760" alt="Screenshot 2024-07-19 at 21 10 32" src="https://github.com/user-attachments/assets/94d6d70f-1250-4147-89ee-3753ee8c1d0b">

**Comment by einpraegsam** [comment]
I can confirm this issue

**Comment by einpraegsam** [comment]
I just released LUX 35.9.0 together with LUXenterprise 40.0.1. The problem should be fixed here.
Thx for reporting!

**Comment by martinpribylhd** [comment]
Thanks for fixing 🥇 :)
