### ISSUE TITLE
Error for companies inside LeadController.

### ISSUE THREAD

**Issue by martinpribylhd** [in2code-de/lux#54]
The action "companies" (controller "In2code\Lux\Controller\LeadController") is not allowed by this plugin / module. Please check TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php / TYPO3\CMS\Extbase\Utility\ExtensionUtility::configureModule() in your ext_tables.php.

How to reproduce:
1) Open Analyses submodule
2) Open tab UTM
3) Choose a lead under the graphs
4) In the lead preview (top left section of the board) click on Show lead details
5) The tabs on top come probably from the Leads submodule (or backend plugin), so the click on "Companies" case an error (the other tabs are fine)

It would be probably just about to add controller name into the tab, but it's only my tip.

Thank you for your hard work :)

**Comment by einpraegsam** [comment]
Hi,

first of all, thx for the feedback.
Can you give me some more information to reproduce the issue:
- TYPO3 version
- Lux version
- Are you using the WiredMinds connection for company information?
- Can you give me a hint where to click to get the failure?

![Screenshot 2024-08-19 at 08-53-01 luxcore localhost de TYPO3 CMS 12 4 12](https://github.com/user-attachments/assets/774a6c0d-56ad-4ef3-a0ff-a401e3a4ad31)

**Comment by martinpribylhd** [comment]
Hi :)

here is a video for 2 days - https://streamable.com/90tffu

TYPO3 - 11.5.38
LUX - 36.2.0

I was just interested what I can find there, it wasn't any plan to use it yet.

In your screen is porbably only to click "Show lead details" in the right top panel called "Lead preview". Then in the next window is the menu for leads, so try to open Companies.

If you miss the video, I can send it then again or make step by step images.

Thank you for your hard and awesome work :)

**Comment by einpraegsam** [comment]
Thx, the video was helpful, I can reproduce the issue even for TYPO3 11 now

**Comment by einpraegsam** [comment]
As a quick fix I just allowed all company related actions also in the Analysis module.

Sooner or later (but not before TYPO3 11 support is dropped) we should change the behaviour to link to the correct module and not allowing every action in every module.

Nevertheless, I just released 36.3.1 with a bugfix.
