### ISSUE TITLE
Lux depending on typo3/cms-ckeditor but dependency is missing in composer.json

### ISSUE THREAD

**Issue by vertexvaar** [in2code-de/lux#6]
I installed a typo3/minimal environment and installed lux. When i try to open the page module i am presented with the exception: `YAML File "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" could not be loaded`.
It seems that lux requires the ckeditor extension but that dependency is missing the composer.json.

**Comment by vertexvaar** [comment]
Does lux really require CKEditor? If not i would opt for removing the code dependency or for introducing a check if ckeditor is installed before trying to access files.

**Comment by einpraegsam** [comment]
Fixed in 4.1.0
