### ISSUE TITLE
TYPO3 10.4.2 Database Maintenance Update Operation lux

### ISSUE THREAD

**Issue by rubensutter** [in2code-de/lux#7]
I discovered that the lux extension (8.1.1) wants to add some database tables but actually can't perform the database query.

Maintenance -> Analyze Database Structure -> Apply selected changes 
results in 

Database Update failed
Error: Key column 'visitor' doesn't exist in table.
(CREATE TABLE tx_lux_domain_model_linkclick...)

This error message is so true, I double-checked and couldn't find a visitor in the table nor the table to which it would seem to me belonging to.

Running the Database update command the classic way results in:
In der Tabelle gibt es kein Schlüsselfeld 'visitor'

**Comment by einpraegsam** [comment]
Thx for reporting. This small issue is related to the upcoming "Link Listener" feature in Lux 9. I just released 8.2.1 to packagist. 
Because you are using the older version 8.1.1 - are you using composer or classic mode?

**Comment by einpraegsam** [comment]
No answer, I will close this issue for now
