### ISSUE TITLE
defaultOrderings in LinkclickRepository

### ISSUE THREAD

**Issue by breakone** [in2code-de/lux#8]
```
...
    /**
     * @var array
     */
    protected $defaultOrderings = [
        'title' => QueryInterface::ORDER_ASCENDING
    ];
...
```

There is no 'title'-field in this table, so an exception occurs.

**Comment by einpraegsam** [comment]
Thx Harald, this is the same issue as related to TCA in 681701906bab733b65e26da2466334fc48ad1846. I pushed a fix. A bugfix release will follow.
